name: C Source Kalman Filter Unit Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [ main ]

jobs:
  kalman-filter-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up system
        run: python3 scripts/setup.py --skip-upgrade
      - name: Run Kalman Filter Unit Tests
        run: python3 scripts/test_filter_source.py
