name: Code Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Update to v3
        with:
          submodules: recursive
      - name: Set up system
        run: python3 scripts/setup.py --skip-upgrade
      - name: Check Code Format
        run: python3 scripts/format.py --dry-run
